### PR TITLE
V1.9 & reapply fixes

### PR DESCRIPTION
**Pull request by ProgrammerDan**
Reapply's Max's fix effectively, but corrects it using COLOR_CHAR instead. Sorry for the bad advice previously, Max.

This also goes ahead and updates to 1.9.2 api although like juke should be safe on earlier API level servers.

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
Untested currently.

**Comment by Maxopoly** [comment]
_bump_

**Comment by Maxopoly** [comment]
Do we still want the color code fixes included here?

**Comment by ProgrammerDan** [comment]
Oy, forgot about this, thought already applied.

**Comment by Maxopoly** [comment]
yeah same

**Comment by ProgrammerDan** [comment]
I'll poke and see what's conflicting.

**Comment by Maxopoly** [comment]
Dont bother if it's effort, it doesnt benefit us right now and a larger refactor would need to redo the color stuff from scratch anyway, basically https://github.com/Civcraft/ItemExchange/issues/25

**Comment by ProgrammerDan** [comment]
Agreed, assuming things aren't working any _worse_ then normal at present, let's just close this and wait for rewrite.

**Pull request closed without merging**
